Repository Rainbow-SSAP/SSAP-GaNeung_MVP, pull requests merged in 2023-12, with the labels that each got.

#215 fix: 심부름 요청서 작성시 일시 선택을 했음에도 DB에 값이 저장되지 않는 문제 #214
  backend/src/main/java/ssap/ssap/service/TaskService.java
Labels: 👾 버그, 우선순위: 🟠 높음, BACKEND

#219 docs(1차 README 작성) #218
  README.md
Labels: 📑 문서, 우선순위: 🟠 높음, FRONTEND

#220 docs(1차 README 수정) #218
  README.md
Labels: 📑 문서, 우선순위: 🟠 높음, FRONTEND

#222 docs(시연 영상 추가)
  README.md
Labels: 📑 문서, 우선순위: 🟠 높음
